### ISSUE TITLE
Incluir variável com os paths do workflow e utilizá-la nas tasks

### ISSUE THREAD

**Issue by luisfmsouza** [ciandt-dev/gulp-boilerplate#10]
Exemplo:

```
var paths = {
    input: 'src/**/*',
    output: 'dist/',
    scripts: {
        input: 'src/js/*',
        output: 'dist/js/'
    },
    styles: {
        input: 'src/sass/**/*.{scss,sass}',
        output: 'dist/css/'
    },
    img: {
        input: 'src/images/**/*.{png,jpg,jpeg}',
        output: 'dist/images/'
    }
};
```

**Comment by luisfmsouza** [comment]
O que vocês acham @rhormens, @williankeller, @patrikpicoli, @lnfnunes ?

**Comment by williankeller** [comment]
Cara, eu acho ótimo! Fica bem mais fácil o gerenciamento,aí não precisa acessa arquivo por arquivo para editar as rotas.

**Comment by patrikpicoli** [comment]
Eu também acho ótimo luisfmsouza, acredito que alem de mais legível, fica mais organizado e padronizado.

**Comment by rhormens** [comment]
@luisfmsouza Bacana vou fazer isso!

**Comment by lnfnunes** [comment]
Caras, ontem eu achei um modelo que curti pra caramba.
Fica tudo num arquivo de config e as tasks separadas também. Acho que vai bem nessa linha que vc está propondo.
Vou ver se acho aqui e mando pra vcs verem.

**Comment by luisfmsouza** [comment]
Opa, valeu @lnfnunes ! :)
O @rhormens implementou uma função getTask(), pra fazer load somente dos módulos que precisamos, dá uma conferida no gulpfile.js.

**Comment by luisfmsouza** [comment]
@rhormens inclui a URL do localhost nesse JSON também, ex:

```
var paths = {
    ...
    url: 'cit.local'
    ...
}
```

**Comment by lnfnunes** [comment]
Eu vi @luisfmsouza, ficou bem show!
Outra sugestão é incluir também config dinâmica para copy simples de assets variados:
```javascript
var paths = {
  ...
  assets: [{
    fonts: {
      input: 'src/fonts/**/*.{eot,svg,woff,ttf}}',
      output: 'dist/fonts/'
    },
    svg: {
      input: 'src/images/**/*.svg',
      output: 'dist/images/'
    }
  }]
  ...
}
```

**Comment by lnfnunes** [comment]
@rhormens fiquei na dúvida aqui! Vc já iniciou essa implementação do config.js contendo os paths dinâmicos para cada tarefa ?

**Comment by luisfmsouza** [comment]
Acho que ele iniciou sim. @rhormens tem previsão de commitar?

**Comment by williankeller** [comment]
@rhormens, @luisfmsouza, quando terminarem essa issue, passem pra mim criar a documentação de alteração dessas rotas de paths
