### ISSUE TITLE
Como contribuir neste repositório?

### ISSUE THREAD

**Issue by luisfmsouza** [ciandt-dev/gulp-boilerplate#23]
Acho interessante termos um checklist simples de como contribuir, para ajudar todos a contribuirem. Ex:

- [ ] Incluir módulo? Adicionar todas as dependências e testar.
- [ ] Incluir no README.md a referência
- [ ] Referenciar a issue no commit, ex: Issue #95: descrição do que foi feito
- [ ] Submeter Pull Request, também referenciando a Issue
- [ ] PR aceito? Feche a issue

**Comment by luisfmsouza** [comment]
@williankeller, @rhormens, @patrikpicoli, @lnfnunes acham válido? Incluiriam alguma outra coisa?

**Comment by williankeller** [comment]
Muito bom!
Ótima sugestão na verdade, desta forma, garantimos que todos os processos são feitos corretamente.
Principalmente referenciar a "Issue".

**Comment by lnfnunes** [comment]
Acho ótimo! Vejo essa prática em vários repositórios. +1

**Comment by rhormens** [comment]
Acho que é isso mesmo, não esquecendo de fechar a issue depois do merge!

**Comment by lnfnunes** [comment]
Quem fecha a issue é quem authorizou o merge ou quem fez o PR ?

**Comment by luisfmsouza** [comment]
Acho que podemos combinar o seguinte:
- Quem submeteu o PR, não pode aprová-lo
- A issue é sempre fechada por quem autorizou o PR

O que acham?

**Comment by rhormens** [comment]
Beleza pode ser! Quem aprova o Pull Request fecha a Issue e caso ela ainda não esteja totalmente fechada? Devemos comentar?

**Comment by luisfmsouza** [comment]
Se faltar algum item, podemos fazer o seguinte na description da issue e/ou pull request:

- [x] Done itens
- [ ] Pending itens

**Comment by luisfmsouza** [comment]
Primeira versão no ar: https://github.com/ciandt-dev/gulp-boilerplate/blob/master/CONTRIBUTING.md

Comentem e corrijam o texto, por favor!
