### ISSUE TITLE
Gulp - Versão minima do node.js

### ISSUE THREAD

**Issue by dsoldera** [ciandt-dev/gulp-boilerplate#25]
Olá,

Fazendo um teste clonei a pasta, depois o npm install encontrei alguns erros. Me parece que é incompatibilidade com minha versão do node (node 10.33) que precise fazer um downgrade para usar uma feature em outro projeto.

Existe alguma versão minima do Node.js para que o projeto funcione?

Abs,

Danielle

**Comment by luisfmsouza** [comment]
Oi Dani, tem como postar aqui um screenshot com a tela do erro?

Talvez tenha algum módulo que tenha essa dependência, mas acredito que ninguém havia notado isso até então.

**Comment by dsoldera** [comment]
Claro.

Segue dois print screen do final do erro para o começo.

![error-gulp-boilerplate-1](https://cloud.githubusercontent.com/assets/11474555/10374188/20674818-6dc8-11e5-9cfb-67773a103367.png)
![error-gulp-boilerplate-2](https://cloud.githubusercontent.com/assets/11474555/10374187/20646c06-6dc8-11e5-82af-c277125124ca.png)

**Comment by luisfmsouza** [comment]
@dsoldera tenta instalar o gulp globalmente( `npm install gulp -g` ), e tente novamente o `npm install`

**Comment by dsoldera** [comment]
Luis,

Tentei os comandos mas o erro continua. =(

**Comment by dsoldera** [comment]
Olá Luis,

Eu instalei a nova versão do Node.js (v4). Removi a pasta node_modules e instalei de novo.

Agora está dando um erro diferente:

![error-gulp-boilerplate-3](https://cloud.githubusercontent.com/assets/11474555/10377865/0ab27a60-6ddc-11e5-95fd-41d73d47acee.png)

**Comment by lnfnunes** [comment]
Tente isso:
```shell
rm -rf node_modules
npm cache clear
npm install
```

**Comment by dsoldera** [comment]
@lnfnunes deu certo!!!

Obrigada! =)

**Comment by lnfnunes** [comment]
:+1:
