### ISSUE TITLE
gulp-minify-css e gulp-imagemin

### ISSUE THREAD

**Issue by dsoldera** [ciandt-dev/gulp-boilerplate#26]
Olá,

Verifiquei que no projeto não tem instalado o gulp-minify-css, assim como não consta as configuração para o gulp-imagemin. Iremos utlizá-los?

Se sim, posso tentar instalar/criar a configuração e fazer um pull request. 

No aguardo da confirmação, para não haver dúvidas. 

Abs,

Danielle

**Comment by luisfmsouza** [comment]
Mandaver Dani!

Deixei essa issue pro minify-css, e criei uma issue separado pro gulp-imagemin, assim facilita pra você ou outra pessoa que queira adicionar ele. :)

**Comment by rhormens** [comment]
@dsoldera @luisfmsouza imagemin já existe da uma olhada está reduzindo o sprite

**Comment by luisfmsouza** [comment]
Acho melhorar desacoplar.
Deixa ele otimizando todas as imagens da pasta `src`, e mandando pra `dist`.


Att,

*Luís Felipe Souza*

2015-10-08 15:10 GMT-03:00 Rafael Rhormens <notifications@github.com>:

**Comment by lnfnunes** [comment]
@luisfmsouza +1

**Comment by luisfmsouza** [comment]
Ahh, uma coisa que eu lembrei agora, acho que não precisamos do css-minify,
o próprio módulo sass já faz isso :D

On Thursday, 8 October 2015, Leandro Nunes <notifications@github.com> wrote:

> @luisfmsouza <https://github.com/luisfmsouza> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ciandt-dev/gulp-boilerplate/issues/26#issuecomment-146670256>
> .
>


-- 

Att,

*Luís Felipe Souza*

**Comment by luisfmsouza** [comment]
Thanks @lnfnunes !
