### ISSUE TITLE
Incluir gulp-imagemin

### ISSUE THREAD

**Issue by luisfmsouza** [ciandt-dev/gulp-boilerplate#28]
Ele já está no README.md, mas ainda não tem a task.

Referência: https://github.com/sindresorhus/gulp-imagemin

**Comment by rhormens** [comment]
@luisfmsouza está sendo utilizado junto com o a geração de sprite. 
Vc acha melhor criarmos uma task para mitificar as imagens em outro diretório?

**Comment by luisfmsouza** [comment]
@rhormens sim, melhor ter uma task separada. Geralmente temos mais imagens além dos sprites, e é bacana otimizar todas.
