### ISSUE TITLE
Plugin para verificar CSS

### ISSUE THREAD

**Issue by dsoldera** [ciandt-dev/gulp-boilerplate#32]
Olá,

Precisariamos inserir um verificação de scss ou de mesmo de css.

Existem dois:
1 - https://github.com/juanfran/gulp-scss-lint - muito bom mas precisa do Ruby

2 - https://www.npmjs.com/package/gulp-csslint - muito bom, não precis de Ruby porém não verifica o scss e precisaria rodar antes da minificação do css (acredito eu).

Como faremos?

Abs,

Danielle

**Comment by luisfmsouza** [comment]
Muito bem levantado Dani!

Eu até tinha criado uma issue pra incluirmos o scss_lint, mas pensando melhor, poderiamos usar o PostCSS pra fazer isso também.

@lnfnunes vc já chegou a usar o PostCSS pra fazer validação de qualidade? Me lembro de vc ter comentado algo sobre.

**Comment by lnfnunes** [comment]
@luisfmsouza para validar não. Só o autoprefixer. Para validar uso o csslint mesmo.
Chegamos a conversar sobre isso aquele dia da talk, não vejo muita diferença em rodar o lint sobre o scss ou css. Particularmente prefiro rodar sobre o css que é o resultado final gerado.

**Comment by luisfmsouza** [comment]
Concordo.

E o argumento da @dsoldera sobre Ruby já tinha me convencido.

Encontrei esse linter, que roda no PostCSS, o que acham?

https://github.com/stylelint/stylelint

**Comment by dsoldera** [comment]
@luisfmsouza parece bom. 

Vou fazer alguns testes com ele.
