### ISSUE TITLE
Incluir integração com o travis.ci

### ISSUE THREAD

**Issue by lnfnunes** [ciandt-dev/gulp-boilerplate#51]
Obs: validar o badget

**Comment by luisfmsouza** [comment]
Já que vai ser integrado com o Travis, poderíamos escrever testes pro próprio Gulpfile.

Alguma sugestão de como fazer testes nas tasks do Gulpfile?

cc @williankeller

**Comment by lnfnunes** [comment]
Exato @luisfmsouza. É essa a ideia! :+1:

**Comment by williankeller** [comment]
Sim, recentemente eu lancei o teste em um boiler do gulp que eu tenho.
O único problema que eu vejo, é de como vincular a conta da CI&T no travis, com quem teriamos que falar.
Eu já posso criar o arquivo travis.ci e inserir as condições de teste lá

**Comment by luisfmsouza** [comment]
Problema de vincular, técnicamente não tem nenhum impedimento.

Sua preocupação é se existe ou não permissão pra fazer isso?


Att,

*Luís Felipe Souza*

Em 5 de novembro de 2015 13:45, Willian Keller <notifications@github.com>
escreveu:

**Comment by lnfnunes** [comment]
Acabei de cair, sem querer, em outro cara de CI que me parece ter um propósito parecido com o travis.
Já testei com sucesso no meu repo forkado. Não sei se conhecem https://codeship.com...
Logo mais eu integro ele aqui no ciandt_dev, blz ?

**Comment by luisfmsouza** [comment]
Interessante!

@williankeller bora rodar os testes que vc comentou ali em cima, com esse carinha?

**Comment by williankeller** [comment]
Demoro galera!
Tipo, eu digo que é complicado a permissão, pq o repo  tem que da ci&t tem que estar lá no travis, tipo, não tem como associar só o boilerplate.

**Comment by williankeller** [comment]
Então @luisfmsouza e @lnfnunes, como eu disse, não consigo ativar o travis pro nosso boiler, olhem uma olhada no print:
![screenshot from 2015-11-17 10 33 34](https://cloud.githubusercontent.com/assets/2963928/11211478/e0b08982-8d16-11e5-9560-bdb38515521c.png)

**Comment by williankeller** [comment]
Fiz o push do arquivo, agora preciso ter acesso pra criar o script de validação seguindo nossas tasks.

**Comment by luisfmsouza** [comment]
Building...

https://travis-ci.org/ciandt-dev/gulp-boilerplate

**Comment by williankeller** [comment]
Boa @luisfmsouza!

Agora consigo criar os scripts, fiquem "avonts" pra ajudar nos testes também ;D
