### ISSUE TITLE
Criação de Script para NPM Test

### ISSUE THREAD

**Issue by waltercassiano** [ciandt-dev/gulp-boilerplate#62]
Conversando com a @dsoldera surgiu a idéia de criar um script para verificar as versões do node/npm e se as mesmas satisfazem ao que está sendo utilizado no gulp-boilerplate. 

Comecei a implementar esse script, e caso tenham mais idéias do que mais poderia vir a  ser incluído ou algo que seria bom testar, enfim quaisquer idéias, só comentar aqui.

**Comment by rhormens** [comment]
Ficou legal @waltercassiano! aceitei seu pull request.
