### ISSUE TITLE
Incluir browser-sync

### ISSUE THREAD

**Issue by luisfmsouza** [ciandt-dev/gulp-boilerplate#7]
Referencia: www.browsersync.io/docs/gulp/

**Comment by lnfnunes** [comment]
Man, eu tenho usado pouco o browser-sync. Voltei a usar o connect com live-reload.
O BS é melhor e mais completo, porém mais pesado consequentemente.

Atualmente no Grunt usamos:
$ grunt server = browser-sync
$ grunt serve = connect + livereload

Oq vcs acham disso? O BS agrega bastante no workflow de vcs ou o connect já é suficiente?

**Comment by luisfmsouza** [comment]
Diria que meio a meio.

Atualmente temos enfrentado problemas de rede com devices pessoais(depois que houveram as mudanças na rede), mas ele ainda salva a pele de muitos devs/testers.

Sobre o connect, eu não conhecia. Vocês conseguem ter a mesma capacidade de acesso as páginas, semelhante ao BS? Notou alguma limitação?

**Comment by lnfnunes** [comment]
Não sei se entendi. Oq seria "a mesma capacidade de acesso as páginas" ?
Internamente o BS usa o Connect... mas ele coloca mais itens em cima, como a sincronia, o weinre, etc.. é como se fosse uma coletânea.

Esses lances da rede lá zuaram mesmo, até por isso acho q diminuimos muito o uso.

De qualquer forma, oq acha da abordagem em ter tanto a task "server" e "serve" ?

**Comment by luisfmsouza** [comment]
Pensei tanto pra escrever, rs mas fim queria apenas dizer: conseguem acessar em qualquer device na rede?

Acho válida, eu mesmo quando estou desenvolvendo gosto de mais agilidade, e todo ms faz diferença. E as vezes algumas coisas do BS fazem falta.

Vou criar uma issue pra criar a task "serve". :+1:
