### ISSUE TITLE
Incluir validação JavaScript

### ISSUE THREAD

**Issue by luisfmsouza** [ciandt-dev/gulp-boilerplate#8]
Usar ESLint: https://github.com/adametry/gulp-eslint

- [x] Incluir ESLint no processo de build
- [x] Incluir configurações do ESLint
- [x] Incluir JsHint/JSCS no processo de build

**Comment by rhormens** [comment]
@luisfmsouza não é melhor usar o jshint(https://github.com/spalger/gulp-jshint)?

**Comment by luisfmsouza** [comment]
@rhormens eu dei uma pesquisada, e alguns artigos me convenceram de que talvez ESLint esteja um pouco a frente dos outros.

Dá uma olhada: http://www.sitepoint.com/comparison-javascript-linting-tools/

**Comment by lnfnunes** [comment]
@luisfmsouza achei meio xarope a configuração do eslint !!
Vê algum problema em colocar jshint + jscs?
Tenho mais familiaridade com esses dois e posso atacar se estiver de acordo...

**Comment by luisfmsouza** [comment]
Eu não vejo problema nenhum, manda bala man! :)

On Wednesday, 14 October 2015, Leandro Nunes <notifications@github.com>
wrote:

> @luisfmsouza <https://github.com/luisfmsouza> achei meio xarope a
> configuração do eslint !!
> Vê algum problema em colocar jshint + jscs?
> Tenho mais familiaridade com esses dois e posso atacar se estiver de
> acordo...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ciandt-dev/gulp-boilerplate/issues/8#issuecomment-148224253>
> .
>


-- 

Att,

*Luís Felipe Souza*

**Comment by luisfmsouza** [comment]
@lnfnunes eu inclui o EsLint, mas fica a vontade pra configurar o JsHint + JSCS

**Comment by lnfnunes** [comment]
@luisfmsouza show!!!
Vou ver aqui depois como ficou... valeu
